### ISSUE TITLE
[BUG] Can't log in to lemmy.ml

### ISSUE THREAD

**Issue by minorsecond** [gkasdorf/memmy#119]
**Describe the bug**
When I try to log in to the lemmy.ml instance, I get `Error Did not receive authentication response.`

I've tried `lemmy.ml` and `https://lemmy.ml` in the Server field

**To Reproduce**
1. Enter either `lemmy.ml` or `https://lemmy.ml` in the server field
2. Populate username and password
3. Tap Add Account

**Expected behavior**
I should be able to log in to lemmy.ml

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5
 - Version: 0.0.1 (57)

**Logs:**
I can't view logs at this stage of logging in

**Comment by gkasdorf** [comment]
Lemmy was updated to 0.18 today. Looks like there may be some breaking changes. I'm going to go through and do what I can to resolve all of them.

**Comment by minorsecond** [comment]
This was happening all week, unfortunately. Sent from my iPhoneOn Jun 22, 2023, at 3:55 PM, Gavin Kasdorf ***@***.***> wrote:﻿
Lemmy was updated to 0.18 today. Looks like there may be some breaking changes. I'm going to go through and do what I can to resolve all of them.

**Comment by gkasdorf** [comment]
Hmm....that's odd. Here's a few questions:

1. Are you using an email or a username to sign in?
2. Without telling me WHAT your password is, can you give me an idea of if it has anything funky about it?
3. Are you able to sign into other instances just not lemmy.ml? What about other accounts on lemmy.ml besides this one (although you might not have one due to closed registration).

Regardless of any of those, it shouldn't matter. Memmy uses the same API client that the web UI uses, so there *shouldn't* be any issues there.

What I'll do is push an update here in the next hour or so that gives details on those failed logins (I think they fixed the fact that it gave a generic response instead of an informative one, which is why I also gave a generic one...) Download that and see what the error is, then we can go from there. I'll reply to this again whenever I do update.

Sorry about this!

**Comment by minorsecond** [comment]
I don’t have any other Lemmy accounts so I haven’t tried that. My password is just a simple alphanumeric one. I’m using just my username. Sent from my iPhoneOn Jun 22, 2023, at 4:21 PM, Gavin Kasdorf ***@***.***> wrote:﻿
Hmm....that's odd. Here's a few questions:

Are you using an email or a username to sign in?
Without telling me WHAT your password is, can you give me an idea of if it has anything funky about it?
Are you able to sign into other instances just not lemmy.ml? What about other accounts on lemmy.ml besides this one (although you might not have one due to closed registration).

Regardless of any of those, it shouldn't matter. Memmy uses the same API client that the web UI uses, so there shouldn't be any issues there.
What I'll do is push an update here in the next hour or so that gives details on those failed logins (I think they fixed the fact that it gave a generic response instead of an informative one, which is why I also gave a generic one...) Download that and see what the error is, then we can go from there. I'll reply to this again whenever I do update.
Sorry about this!

**Comment by gkasdorf** [comment]
Issue was resolved by the user with a password reset. Seems to have been an issue with Lemmy.
