### ISSUE TITLE
[MEM-59] [BUG] Problems loading posts in some communities

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#140]
I'm having trouble loading posts in some communities (not sure if they are related issues, keeping in one bug for now). Web browser confirms there are many posts in these communities.

1) https://lemmy.world/c/crazyfuckingvideos

Memmy does not load *any* posts for this community. It just shows the loading spinner forever (and flashes the community logo a few times). 

2) https://lemmy.world/c/videos

Memmy loads 8 posts from this community. Even if I scroll down, no more load.

3) https://lemmy.world/c/videoessays

Memmy loads 6 posts from this community. Even if I scroll down, no more load.

Is there a problem post in these communities that is preventing the rest from loading? The first case (crazyfuckingvideos) looks pretty bad with all the flashing.

Memmy 0.0.1 (66)
iOS 16.5.1

<sub>[MEM-59](https://linear.app/memmyapp/issue/MEM-59/[bug]-problems-loading-posts-in-some-communities)</sub>

**Comment by gkasdorf** [comment]
Yea, known issue I saw with a recent change. I'll update you once I get a fix. Should be tonight. Thanks! 👍

**Comment by gkasdorf** [comment]
@JeremyLeland Can you verify this is still happening for you? I 100% could repro before, but now seems to be resolved. Wondering if this was some sort of issue with lemmy.world.

**Comment by JeremyLeland** [comment]
Still happening for me on 0.0.1 (66).

**Comment by gkasdorf** [comment]
Ok cool, I'll try to repro again. Same communities that you listed above?

**Comment by JeremyLeland** [comment]
Yep. Crazyfuckingvideos is the most dramatic, since it keeps flickering and never loads anything.

**Comment by gkasdorf** [comment]
I might have unintentionally resolved this in one of my recent modifications. I had been playing with some performance tweaks, and I think I made an error. Now I am no longer getting the issue. Let's see if it happens on .67 whenever I release it. I can not repro this right now, but I know for a fact that it was an issue, so it might just be .66.

**Comment by gkasdorf** [comment]
@JeremyLeland Ok I just pushed the new update. See if it still happens and if so I'll try and resolve it now.

**Comment by JeremyLeland** [comment]
Still repros for me in 0.0.1 (67). (I confirmed my other issue with collapsing comments is resolved, but I’m still hitting this one.)

Is anyone else having issues loading the crazyfuckingvideos community?

**Comment by gkasdorf** [comment]
How many posts are you seeing in the community? For me, I am getting all of them that are available on the website. Also signed in with a lemmy.world account.

**Comment by JeremyLeland** [comment]
For crazyfuckingvideos, I’m not seeing any posts at all. The community never loads. It’s a loading spinner forever, with occasional flashes of the logo. Video:

https://github.com/gkasdorf/memmy/assets/50390633/3bf5b70d-90a8-4a4c-8906-6b7f355c5058

**Comment by gkasdorf** [comment]
I'm going to work on this today.

**Comment by gkasdorf** [comment]
@JeremyLeland Ok so I think I know the issue. It was twofold.

The list that rendered all of the items was configured to load more items whenever the screen reached the end. Since there were no items to render, it would try to load more, and so on and so forth. This is fixed.

The other issue I would like to confirm with you. Are you trying to sort by new for the day? If so, I believe this to be something that I could fix, but also to be an issue with Lemmy. If you are sorting by day, it will not get any posts AFTER that day. I think it should start listing items after that day, but we will see what Lemmy does about that. I can implement some fix I suppose to deal with this better though.

I'm going to close this as I *believe* those to be the two issues. Please let me know if this is not the case and we will go from there.

Thanks!

**Comment by gkasdorf** [comment]
Is new by day your default search option selected? I think that might be the issue. It might be worth changing that whenever you open a community. Probably should be separate from the main feed setting.

And yea, we could do that. It's just weird to have to differentiate between "well there's no more content because of your selection" and "there's no more content because there is no more content". Maybe it's worth just trying to change the value to new once there's no more content and loading that instead.
