### ISSUE TITLE
Blocked communities show up in feed

### ISSUE THREAD

**Issue by aboodvan** [gkasdorf/memmy#285]
**Describe the bug**
Blocked communities show up in the feed.

**To Reproduce**
1. Go to feed
2. Block a community
3. Refresh the feed
4. Scroll until it load more posts
5. Posts from the blocked community appears

**Expected behavior**
Blocked communities would not show up

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 16.5.1 (20F75)
 - Version 0.0.2 (6)

**Comment by gkasdorf** [comment]
I just tried to reproduce this and it seems to work for me.

My guess is that the instance you were using had a connection issue and the block request did not successfully go through (it should let you know about that...I'll make sure). But yea, probably a bad connection today given all the traffic.

**Comment by feyder213** [comment]
> I just tried to reproduce this and it seems to work for me.
> 
> My guess is that the instance you were using had a connection issue and the block request did not successfully go through (it should let you know about that...I'll make sure). But yea, probably a bad connection today given all the traffic.

Since the last update in TestFlight previously blocked communities appear in my feed again. However, when I go to the community to block the meatball menu is gone and replaced by a globe that gives the the options for displaying feed sort order. Also when visiting a blocked community no actual posts appear on the community. Attaching some screenshots https://imgur.com/a/zIbrDYU

**Comment by aboodvan** [comment]
Working now as intended for me. It did happen 2 days ago but it was signing in and out so I just removed the account and sign in again.

Now seems to be working like a charm.
