### ISSUE TITLE
Unable to Parse JSON

### ISSUE THREAD

**Issue by hugpeter** [gkasdorf/memmy#287]
**Describe the bug**
Getting an error pop up when submitting comments or editing comments that says unable to parse JSON. The comment still gets posted, and the edit also still goes through so this must just be a parsing error on returned json after the call is made. 

**To Reproduce**

Make a comment on a post. Then edit that same comment. 

**Expected behavior**
It should show the loading symbol then load the post again with the new comment in view. 

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/26207788/8e2c0914-b366-424c-814a-258f9e0ea4ec)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: ios 16.5.1
 - Version 2.()

**Comment by gkasdorf** [comment]
This is an error being received from the server you're using. I agree that the error messages need to be better, but we don't actually get a good response back from the API. However, I'm going to do something so that it isn't as janky.

Regardless, the server load many instances are experiencing right now is what causes that, and it isn't a direct issue with Memmy.
