### ISSUE TITLE
[BUG] scrolling through the main feed quickly results in an error

### ISSUE THREAD

**Issue by z01L** [gkasdorf/memmy#35]
**Describe the bug**
If you quickly scroll through the main feed, Memmy will throw an error saying “Error loading content :(“

**To Reproduce**
1. On the main feed, show all posts
2. Scroll down really quickly

**Expected behavior**
No error or a loading screen while it retries

**Screenshots**
https://streamable.com/93q6mo

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.5
 - Version 0.0.1(18)

**Comment by gkasdorf** [comment]
Yea, this just has to do with the unreliable connection to the lemmy instances. But it shouldn't be completely wiping your feed, so I'll have it retry up to three times then just display a 😢 if it can't get through by then.

**Comment by z01L** [comment]
Or a less obtrusive error and allow the user to retry without losing their position in the feed.

**Comment by gkasdorf** [comment]
> Or a less obtrusive error and allow the user to retry without losing their position in the feed.

There will be a message, but it will just be a button at the bottom of the screen instead of full screen.

On that note, posting comments and up/down voting can do the same. You may have noticed that a vote sometimes will register but will quickly change back to neutral. This is because I'm updating the state, attempting to vote, then resetting the state if it was unsuccessful. I think this is fine but I'll make a little notification at the bottom of the screen letting you know the request failed.

As for comments, I'll leave it alone for now until I finish the markdown stuff and revamp the comment view. The error saying failed is enough to know to just submit again.

**Comment by z01L** [comment]
An update on this, I only started experiencing this problem after upgrading to 0.0.1(18). Since upgrading, it errors quite a bit. Even when I'm scrolling through the feed slowly.

I wonder if it has anything to do with the de-duplication fix?

**Comment by gkasdorf** [comment]
Hmm that's a good question. What instance are you on by the way? If we are both experiencing this but on different instances then there's a chance it might be something related to that.

**Comment by z01L** [comment]
I’m on lemmy.nz but also tested it on beehaw.org.

Not sure if it’s anecdotal but it feels like it errors quicker on subscribed than all. Using “hot” sorting for both tests.

**Comment by TysonCodes** [comment]
I also experience this with 0.0.1(19) slowly scrolling. It seems to get to a point where the posts repeat and if you keep going you get the error. Going to the website there is no issue but you of course need to use the ‘next’ button to get more posts from the next page. I suspect it’s not time-out related.

**Comment by gkasdorf** [comment]
Took a little while but found the issue. Fixing now!

**Comment by gkasdorf** [comment]
Fixed. Will be released tonight.
