### ISSUE TITLE
[BUG] White screen when loading some links

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#96]
**Describe the bug**
Tapping some links leads to a completely white screen, requiring the app to be forcibly closed. This particular link is to a kbin community.

**To Reproduce**
1. Go to https://lemmy.world/post/317749
2. Tap one of the links for "https://kbin.social/m/NursingMatters"

**Expected behavior**
NursingMatters community should open, either in browser or new Community view

**Actual Behavior**
The screen goes completely white, with no obvious way to go back. I had to force quit the app.

This happened with both the blue underlined link and the styled gray box with the "link" icon.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16.5
 - Version 0.0.1 (49)

**Additional context**
The HTML for the post in question is:

```
<div class="md-div"><p>Hi all.  For all those who are nurses, work with nurses, want to be nurses, or have general interest in the nursing field, please come visit us at @NursingMatters@kbin.social
<a href="https://kbin.social/m/NursingMatters">https://kbin.social/m/NursingMatters</a></p>
</div>
```

The only notable thing about the link (for me) is that it's to a kbin page. (Not sure if that's actually the problem in this case.)

**Comment by gkasdorf** [comment]
Is it all KBin links or just some?

**Comment by JeremyLeland** [comment]
Not all, apparently. This one works: https://lemmy.world/post/294025

```
<div class="md-div"><p>This community is dedicated to all things Signal Messenger, the open-source secure and private messaging app developed by the non-profit Signal Foundation.</p>
<p><a href="https://kbin.social/m/Signal">https://kbin.social/m/Signal</a></p>
</div>
```

So maybe it doesn't have anything to do with kbin. Must be something about the NursingMatters page specifically.

**Comment by JeremyLeland** [comment]
When I navigate to https://kbin.social/m/NursingMatters in web browser, it shows that there are no posts yet (page just says "empty" under the headings). Maybe that's part of the problem?
![empty NursingMatters page](https://github.com/gkasdorf/memmy/assets/50390633/abe48fbb-680b-4352-97a1-f441396352ac)

**Comment by gkasdorf** [comment]
Ahh I think I did hear something about this. And it might not actually be KBin specific.  Interesting that it's causing a crash though, wonder what error this is throwing that isn't handled. Let me take a look now.

**Comment by gkasdorf** [comment]
> When I navigate to https://kbin.social/m/NursingMatters in web browser, it shows that there are no posts yet (page just says "empty" under the headings). Maybe that's part of the problem? ![empty NursingMatters page](https://user-images.githubusercontent.com/50390633/247010415-abe48fbb-680b-4352-97a1-f441396352ac.png)

So this is weird. Whenever I visit that magazine either in development or in production, I just get the community not found page. Specifically, the response that you receive from the Lemmy API is: `error: "couldnt_find_community"`.

The signal link works fine just as you said. This is a real weird one, and it's going to take some investigating

**Comment by gkasdorf** [comment]
I see that there are some additional characters before some of these links (one that caused a crash for me just now includes a %5B, or a [, infront of the URL). As far as the crash, it looks like it's an unhandled error in expo-web-browser that is causing it, outside of my immediate control. Attempting to catch the error doesn't help (in fact, even in developer builds with agressive error handling, there is no caught exception). I've opened an issue about this here. https://github.com/expo/expo/issues/22986

Regardless, this issue brought me to another one. It looks like in my attempt to not only parse regular markdown links but also parse ones that are not wrapped in markdown, I made an error with the regex, resulting in a stray [ being in front of the URL.

I've corrected that issue now. I am also going to continue matching URLs before they are opened to be sure they are valid (either typos or malicious attempts could cause some issues here, I suppose, so better to be safe than sorry).

This is only one issue with the crashes. I will still look into what is causing those white screen issues, since that might be a separate issue. Please let me know if you find any other instances of this happening.

**Comment by b-bayport** [comment]
I experience the same white screen crash for Old Maps community 
https://mander.xyz/c/old_maps

Thru Memmy I get the white screen crash
Thru web browser I get the community page and has no posts nor comments

**Comment by JeremyLeland** [comment]
Here’s another white screen link:

https://lemmy.world/comment/104769 (from https://lemmy.world/post/45688)

the third link on that comment:

“*I’m not sure of the intended way to link communities from other instances but this should allow .world users to subscribe at the .ca one: [https://lemmy.world/c/bestofthefediverse@le](https://lemmy.world/c/bestofthefediverse@lemmy.ca)
“

Clicking that third link gives me a white screen. The community has posts, so I’m not sure if this has anything to do with kbin or empty communities. Changed title to be more general.

**Comment by gkasdorf** [comment]
> Here’s another white screen link:
> 
> https://lemmy.world/comment/104769 (from https://lemmy.world/post/45688)
> 
> the third link on that comment:
> 
> “*I’m not sure of the intended way to link communities from other instances but this should allow .world users to subscribe at the .ca one: [https://lemmy.world/c/bestofthefediverse@le](https://lemmy.world/c/bestofthefediverse@lemmy.ca) “
> 
> Clicking that third link gives me a white screen. The community has posts, so I’m not sure if this has anything to do with kbin or empty communities. Changed title to be more general.
> 
> (I’ll post the HTML when I get to my desktop)

I expect the comment and post links might be causing crashes because I have not fully implemented going to those items from a link, only communities. I'll look into that, but regardless within the next day or so it shouldn't be an issue anymore.

The more concerning thing to me right now is links that are NOT lemmy/kbin instances and are causing crashes. Have you ran into any more of those?

**Comment by z01L** [comment]
I’m encountering this issue when clicking on a link to a community where there are no posts.

To replicate this, set the default sort to TopDay so that only posts from the last 24 hours show up. Then click on a link to a community with no posts in the past 24 hours. Result=White screen.

I suspect it’s something to do with handling a null/empty response?

**Comment by gkasdorf** [comment]
> I’m encountering this issue when clicking on a link to a community where there are no posts.
> 
> To replicate this, set the default sort to TopDay so that only posts from the last 24 hours show up. Then click on a link to a community with no posts in the past 24 hours. Result=White screen.
> 
> I suspect it’s something to do with handling a null/empty response?

Most likely yes. I'll take a look before I push tonight's release and see if I can fix that. I've had the same experience a few times. Cheers.

**Comment by gkasdorf** [comment]
Cool, thanks for letting me know. I’ll see if I can do something to give more intelligent responses to those errors (although it’s hard since the Lemmy API is also broken right now and is in the process of being fixed). Regardless, in future versions I plan on having a better way to deal with user onboarding to make it super easy and understandable to find and sign up for an instance.

Let me know if you need any other help, cheers!

**Comment by gkasdorf** [comment]
Should be fixed in next update. https://github.com/gkasdorf/memmy/pull/108
